Data Encoding

Nominal/OHE Encoding

In [44]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [45]:
## Create a simple dataframe

df=pd.DataFrame({
    'color': ['red','blue','green','red','blue']
})

In [46]:
df.head()

   color
0    red
1   blue
2  green
3    red
4   blue

Converting Categorical features into numerical features

In [ ]:
##create a instance of onehotencoder : We need OneHotEncoder() to create a reusable tool that automatically converts categorical values into numbers in a way ML models can understand.
encoder=OneHotEncoder()

In [12]:
##Perform fit and transform
encoded = encoder.fit_transform(df[['color']]).toarray()

In [18]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [19]:

encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0

In [ ]:
# For new Data
encoder.transform([['blue']]).toarray()

c:\Users\archa\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [28]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3    red         0.0          0.0        1.0
4   blue         1.0          0.0        0.0

In [1]:
import seaborn as sns

In [37]:
dataset = sns.load_dataset('tips')
dataset
df1 = pd.DataFrame(dataset)
df1

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [38]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [39]:
encoder1=OneHotEncoder()

In [40]:
encoded1 = encoder1.fit_transform(df1[['total_bill','sex']]).toarray()

In [41]:
import pandas as pd
encoder1_df=pd.DataFrame(encoded1,columns=encoder1.get_feature_names_out())

In [42]:
encoder1_df

,total_bill_3.07,total_bill_5.75,total_bill_7.25,total_bill_7.51,total_bill_7.56,total_bill_7.74,total_bill_8.35,total_bill_8.51,total_bill_8.52,total_bill_8.58,...,total_bill_41.19,total_bill_43.11,total_bill_44.3,total_bill_45.35,total_bill_48.17,total_bill_48.27,total_bill_48.33,total_bill_50.81,sex_Female,sex_Male
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
240,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
241,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
242,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
243,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

Label Encoding

In [47]:
df.head()

   color
0    red
1   blue
2  green
3    red
4   blue

In [48]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [49]:
lbl_encoder.fit_transform(df[['color']])

c:\Users\archa\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 2, 0])

In [50]:
lbl_encoder.transform([['red']])

c:\Users\archa\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [51]:
lbl_encoder.transform([['blue']])

c:\Users\archa\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

Ordinal Encoding

In [53]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [54]:
df2= pd.DataFrame({
    'size' : ['small','medium','large','medium','small','large']
})

In [55]:
df2

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [ ]:
## Create  a instance of ordinal encoder and then fit_transform
encoder = OrdinalEncoder(categories=[['small','medium','large']])

## Categories used to give ranks to the data we want to transform

In [57]:
encoder.fit_transform(df2[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [58]:
## Giving new data
encoder.transform([['small']])

c:\Users\archa\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

Target Guided Ordinal Encoding

In [60]:
df3 = pd.DataFrame({
    'city': ['New York','London','Paris','Tokyo','New York','Paris'],
    'price': [200,150,300,250,180,320]
})

In [61]:
df3

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [64]:
mean_pricce= df3.groupby('city')['price'].mean().to_dict()

In [65]:
mean_pricce

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [ ]:
df3['city_encoded'] = df3['city'].map(mean_pricce)

In [68]:
df3

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0

In [69]:
df3[['price','city_encoded']]

   price  city_encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0