In [2]:
import numpy

In [2]:
import pandas as pd

In [ ]:
## Series -> Pandas series is a one dimensional array like object that can hold any data type, It is similar to a column in a table

import pandas as pd

data=[1,2,3,4,5]
series=pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
## Series from dictionary 

data={'a':1,'b':2,'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [5]:
data = [10,20,30]
index=['a','b','c']

pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [ ]:
#Dataframe -> Tabular form
#Create a dataframe from a dictionary of list

data={
    'Name':['Abhay','Raj','John'],
    'Age':[25,30,45],
    'City':['Bangalore','New York','Texas']
}

df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Abhay   25  Bangalore
1    Raj   30   New York
2   John   45      Texas
<class 'pandas.core.frame.DataFrame'>

In [18]:
## Create a dataframe from a list of dictionaries

data=[
   {'Name':'Abhay','Age':32,'City':'Bangalore'},
    {'Name':'Raj','Age':21,'City':'Gkp'},
    {'Name':'Bappy','Age':32,'City':'Jhk'},
]
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Abhay   32  Bangalore
1    Raj   21        Gkp
2  Bappy   32        Jhk
<class 'pandas.core.frame.DataFrame'>

In [15]:
af= pd.read_csv('data.csv')
af.head(10)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North
5  2023-01-06        B   54.0  Product3  192.0   West
6  2023-01-07        A   16.0  Product1  936.0   East
7  2023-01-08        C   89.0  Product1  488.0   West
8  2023-01-09        C   37.0  Product3  772.0   West
9  2023-01-10        A   22.0  Product2  834.0   West

In [20]:
#Accessing Data from dataframe
df

    Name  Age       City
0  Abhay   32  Bangalore
1    Raj   21        Gkp
2  Bappy   32        Jhk

In [ ]:
df['Name'] # accessing column

0    Abhay
1      Raj
2    Bappy
Name: Name, dtype: object

In [ ]:
df.loc[0] # row index -> accessing row

Name        Abhay
Age            32
City    Bangalore
Name: 0, dtype: object

In [23]:
df.iloc[0]

Name        Abhay
Age            32
City    Bangalore
Name: 0, dtype: object

In [24]:
## Accessing a specified element 
df

    Name  Age       City
0  Abhay   32  Bangalore
1    Raj   21        Gkp
2  Bappy   32        Jhk

In [29]:
df.at[1,'City']

'Gkp'

In [ ]:
## Accessign a specified element using iat
df.iat[2,2] # both row index and column index

'Jhk'

In [34]:
df

    Name  Age       City
0  Abhay   32  Bangalore
1    Raj   21        Gkp
2  Bappy   32        Jhk

In [35]:
## Data manupulation with Dataframes
df

    Name  Age       City
0  Abhay   32  Bangalore
1    Raj   21        Gkp
2  Bappy   32        Jhk

In [53]:
df['Salary'] = [50000,60000,70000]
df

    Name  Age       City  Salary
0  Abhay   32  Bangalore   50000
1    Raj   21        Gkp   60000
2  Bappy   32        Jhk   70000

In [54]:
## Remove a column
df.drop('Salary',axis=1) ## it is not a permanent operation

    Name  Age       City
0  Abhay   32  Bangalore
1    Raj   21        Gkp
2  Bappy   32        Jhk

In [50]:
df

    Name  Age       City
0  Abhay   32  Bangalore
1    Raj   21        Gkp
2  Bappy   32        Jhk

In [57]:
## Remkve column permanently 
df.drop('Salary',axis=1,inplace=True)

In [58]:
df

    Name  Age       City
0  Abhay   32  Bangalore
1    Raj   21        Gkp
2  Bappy   32        Jhk

In [59]:
## Add age to the column
df['Age']=df['Age']+1
df

    Name  Age       City
0  Abhay   33  Bangalore
1    Raj   22        Gkp
2  Bappy   33        Jhk

In [62]:
df.drop(0,inplace=True) ## by default it will take row value r=0

In [63]:
df

    Name  Age City
1    Raj   22  Gkp
2  Bappy   33  Jhk